<div class="row">

    <?php View::content(); ?>
    <h3>Formulario de registro de profesores</h3>

    <?php echo Form::open(); ?>

        <div class="col s6">
            <label>Nombres
                <?php echo Form::text('profesores.Nombres');?>
            </label>
        </div>

        <div class="col s6">
            <label>Apellidos
                <?php echo Form::text('profesores.Apellidos');?>
            </label>
        </div>

        <div class="col s6">
            <label>Especilidad
                <?php echo Form::text('profesores.Especialidades');?>
            </label>
        </div>

        <div class="col s12">
            <?php echo Form::submit('Guardar', 'class="btn purple darken-2"') ?>
        </div>

    <?php echo Form::close(); ?>

</div>