<?php echo View::content() ?>
<h3>Listado profesores</h3>

<table>
    <tr>
        <thead>
            <th>Id</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Especialidad</th>
            <th>Acciones</th>
        </thead>

        <?php foreach ($ListaProfesores->items as $item) : ?>

            <tr>
                <td><?php echo $item->Id ?></td>
                <td><?php echo $item->Nombres ?></td>
                <td><?php echo $item->Apellidos ?></td>
                <td><?php echo $item->Especialidades ?></td>
                <td>
                <?php echo Html::linkAction("edit/$item->Id/", "Editar", 'class="btn"') ?>
                    <?php echo Html::linkAction("del/$item->Id/", "Borrar", 'class="btn red"') ?>
            </td>
            </tr>

        <?php endforeach ?>
    </tr>
</table>