<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <title><?php echo $titulo ?></title>
</head>

<body>
    <nav class="purple darken-2">
        <ul>
            <li> <a href="http://localhost:81/kumbia/KumbiaPHP-1.1.3/alumnos">Alumnos</a> </li>
            <li> <a href="http://localhost:81/kumbia/KumbiaPHP-1.1.3/alumnos/create">Registro Alumnos</a> </li>
            <li> <a href="http://localhost:81/kumbia/KumbiaPHP-1.1.3/profesores">Profesores</a> </li>
            <li> <a href="http://localhost:81/kumbia/KumbiaPHP-1.1.3/profesores/create">Registro Profesores</a> </li>
        </ul>
    </nav>

    <div class="container">
       <!--<?php View::partial('fecha') ?>-->
        <?php View::content() ?>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>

</html>